---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-secretless-sa
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-secretless
  labels:
    app: cityapp-secretless
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-secretless
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: cityapp-secretless
  name: cityapp-secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-secretless
  template:
    metadata:
      labels:
        app: cityapp-secretless
    spec:
      serviceAccountName: cityapp-secretless-sa
      containers:
      - image: asia.gcr.io/<project name>/cityapp:1.0
        imagePullPolicy: IfNotPresent
        name: cityapp
        env:
          - name: DBAddress
            value: "127.0.0.1"
          - name: DBPort
            value: "3306"
          - name: DBName
            value: "world"
          - name: DBPassword
            value: ""
          - name: DBUsername
            value: ""
        ports:
        - containerPort: 3000
          name: http
      - image: cyberark/secretless-broker:latest
        imagePullPolicy: Always
        name: secretless
        args: ["-f", "/etc/secretless/secretless.yml"]
        ports:
        - containerPort: 3306
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_VERSION
            value: '5'
          - name: CONJUR_APPLIANCE_URL
            value: "https://<conjur fqdn>"
          - name: CONJUR_AUTHN_URL
            value: "https://<conjur fqdn>/authn-k8s/dev"
          - name: CONJUR_ACCOUNT
            value: "default"
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/dev/apps/cityapp/service_account/cityapp-secretless-sa"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-cert
                key: ssl-certificate
        volumeMounts:
          - mountPath: /etc/secretless
            name: config
            readOnly: true
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: config
          configMap:
            name: cityapp-secretless-config
