---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-hardcode
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-hardcode
  labels:
    app: cityapp-hardcode
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-hardcode
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-hardcode
  name: cityapp-hardcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-hardcode
  template:
    metadata:
      labels:
        app: cityapp-hardcode
    spec:
      serviceAccountName: cityapp-hardcode
      containers:
      - image: asia.gcr.io/<project name>/cityapp:1.0
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: DBAddress
            value: "<db fqdn or ip>"
          - name: DBName
            value: "world"
          - name: DBPort
            value: "3306"
          - name: DBUsername
            value: "conjur"
          - name: DBPassword
            value: "<db password>"
        ports:
        - containerPort: 3000
          name: http
