---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-k8s-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-k8s-secrets
  labels:
    app: cityapp-k8s-secrets
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-k8s-secrets
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-k8s-secrets
  name: cityapp-k8s-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-k8s-secrets
  template:
    metadata:
      labels:
        app: cityapp-k8s-secrets
    spec:
      serviceAccountName: cityapp-k8s-secrets
      containers:
      - image: asia.gcr.io/<project name>/cityapp:1.0
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: DBAddress
            value: "<db fqdn or ip>"
          - name: DBName
            value: "world"
          - name: DBPort
            value: "3306"
          - name: DBUsername
            value: "conjur"
          - name: DBPassword
            valueFrom:
                secretKeyRef:
                    name: mysql01-secret
                    key: password
        ports:
        - containerPort: 3001
          name: http
